name: Deploy docker image

on:
  pull_request:
    branches:
      - 'master'
      - 'main'
  push:
    branches:
      - 'master'
      - 'main'

jobs:

  build_docker_image:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Maven Package
        run: mvn -B clean compile package -DskipTests

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: markstav/spring-boot-github-actions-example
          tags: v1.0.1, latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}   
      
#      - name: Run deploy on server
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.SERVER_HOST }}
#          username: ${{ secrets.SERVER_USERNAME }}
#          key: ${{ secrets.SERVER_KEY }}
#          port: ${{ secrets.SERVER_PORT }}
#          script: |
#            sudo docker-compose -f docker-compose.prod-ci.yml -p prod pull
#            sudo docker-compose -f docker-compose.prod-ci.yml -p prod up -d    
